### ISSUE TITLE
add support for UUID v5 construction

### ISSUE THREAD

**Issue by goedelsoup** [ChristopherDavenport/fuuid#136]
This functionality is also not available from `java.util.UUID`, but it is incredibly useful and is fairly straightforward to implement. If this seems like a good home for this, I'm glad to make a PR.

**Comment by wedens** [comment]
Seems like it's already implemented: https://github.com/ChristopherDavenport/fuuid/blob/255a2bce60e98c156f0eda88fe2fe2af820fd709/modules/core/src/main/scala/io/chrisdavenport/fuuid/FUUID.scala#L81

**Comment by ChristopherDavenport** [comment]
It was recently by @LukaJCB
